### ISSUE TITLE
Why is the animation so slowwwwwww...

### ISSUE THREAD

**Issue by jasminexie** [sunshineclt/Gourmand#4]
Please change the timer interval... the animation is so slow!

Good job! This homework is amazing!

_你们竟然有个胃类。。丧心病狂。。而且为啥感觉代码全是你写的+全是swift风格_😂 _didXXXXX什么的_😂

**Comment by sunshineclt** [comment]
🙈Actually there is no animation in our design😂And I don't know how to do animation...Maybe change the timer interval to smaller will do animation work? That's little bit strange😂Like your 扫雷...
The model was written by 胡顺昕，I wrote the controller and you see....It's cocoa style....I don't know what is JAVA style23333 Can I see your JAVA homework last year(or last last year)?

**Comment by sunshineclt** [comment]
Actually this homework is coupling a lot...controller and view are all together...We will split the MVC totally in our middle-term homework. Hope you can review it~

**Comment by jasminexie** [comment]
Wow great!!!! I'm looking forward to it! :) Please tell me if/when you've finished with that!

My midterm homework was badly coded... I mean, REALLY badly coded. We had a model, and but the view and the controller were mixed together in one or two classes. I cringe whenever I look at the code. It's horrendous 😂

I'm rather proud of my final project though :) That was sort of MVC-style with protocols and callbacks... I'll clean up the code and push it on Github when I have time :)

**Comment by jasminexie** [comment]
So, there was NO animation? NO timer at all? o.O Oookay, I didn't really read the code through... That's weird, because I used JLabel + Swing timers to animate my homework last year, and it was pretty fluent. I have no idea why Swing's rendering function is so slow on both your Gourmand and my Minefield... o.O

**Comment by sunshineclt** [comment]
There is no timer actually. 
This application actually works through this process: 
1. the controller opened a thread for every animal.
2. the animal has a "run" method and the controller start it.
3. the "run" method will sleep that thread for some time until the animal eat another bite
4. When the animal eat another byte, it will use the delegate to let controller know he eats a bite
5. The controller refresh the view
So there actually is no animation in our design. And...if you see carefully, you will find my controller and view are all together🙈But in our middle-term homework we have 6 people to do this homework together so I have to separate the MVC, otherwise the division of work will be hard...
Actually it has been created~ In my Github, the "Rakuten Link" project~My teammate create this name saying“乐天消消看”...
Looking forward to seeing your animation work and final project :smile:
